package csebank_managers.asu.edu;

public enum Operation{
	//enum AccountOperation implements Operation{
		VIEW_ACCOUNT, VIEW_ALL_ACCOUNT, ADD_ACCOUNT, DELETE_ACCOUNT, MODIFY_ACCOUNT_INFO, MODIFY_USER_INFO,	 
	//enum TransOperation{
		 	 //non-critical
			VIEW_TRANSACTION, ADD_TRANSACTION, MODIFY_TRANSACTION, DELETE_TRANSACTION, AUTHORIZE_TARNS_NC,
			 //critical
			AUTHORIZE_TARNS_C,
	// RequestOperation{
		 VERIFY_EXTUSER_REQUEST, VERIFY_REG_EMPLOYEE_REQUEST, REQUEST_PERSONAL_ACCOUNT_MODIFICATION,
	//admin tasks
		 VIEW_EMPLOYEE, ADD_EMPLOYEE, DELETE_EMPLOYEE, MODIFY_EMPLOYEE_DETAIL,
		 ACCESS_SYSTEM_LOG, VERIFY_MANAGER_EMPLOYEE_REQUEST, ACCESS_PII,
	//regular user tasks
		DEBIT_MONEY, CREDIT_MONEY, TRANSFER_MONEY,
	//merchant tasks
		SUBMIT_EXT_USER_PAYMENT;	
	}